# -*- mode: python -*-

a = Analysis(['book.py'],
             pathex=['/path/to/book'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             noarchive=False,
             native_libs=[],
             strip=False,
             upx=True,
             upx_exclude=[],
             runtime_tmpdir=None,
             console=False,
             disable_windowed_traceback=False,
             argv_emulation=False,
             add_data=['templates'],
             manifest=None,
             icon=None,
             version=None,
             company_name=None,
             copyright=None,
             name='book',
             no_dependencies=False,
             embed=False,
             warn_no_deps=False,
             key=None,
             cert=None,
             onefile=False,
             onedir=False,
             ascii=False,
             debug=False,
             strip_dir=None,
             environnement=[],
             spec_file=None,
              optimize=0,
             noupx=False,
             app_manifest='pyinstaller.manifest',
             runtime_library_dir=None,
             strip_ext=False,
             pyz=False,
             collect_submodules=True,
             optimize_import_path=True)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='book',
          debug=False,
          strip=False,
          upx=True,
          console=True,
           icon='book.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='book')
